### cover_nan.py에서 결측치를 해결한 train 데이터셋 가져오기

In [ ]:
import sys
import os
import pandas as pd

# 현재 작업 디렉토리 경로를 가져옵니다.
current_dir = os.getcwd()

# 노트북의 위치가 './다훈'이라면 상위 디렉토리로 이동하기 위해
# '../'를 사용하여 경로 조정. 'shared codes' 디렉토리 경로를 sys.path에 추가합니다.
shared_codes_dir = os.path.join(current_dir, '../shared codes')
sys.path.append(shared_codes_dir)

# 이제 cover_nan 모듈을 임포트할 수 있습니다.
from cover_nan import missing_value_removal_function

train = pd.read_csv("../shared codes/data/train.csv")
# missing_value_removal_function 사용
df = missing_value_removal_function(train)

## 전처리

### bool 컬럼 만들기

In [57]:
binary_columns = [col for col in df.columns if df[col].dropna().isin([0, 1]).all()]

print("0 또는 1만 포함된 컬럼:", binary_columns)

# 해당 컬럼들을 bool 타입으로 변환하기
for col in binary_columns:
    df[col] = df[col].astype(bool)

print(df.dtypes)

# df[binary_columns].head()

0 또는 1만 포함된 컬럼: ['배란 자극 여부', '단일 배아 이식 여부', '남성 주 불임 원인', '남성 부 불임 원인', '여성 주 불임 원인', '여성 부 불임 원인', '부부 주 불임 원인', '부부 부 불임 원인', '불명확 불임 원인', '불임 원인 - 난관 질환', '불임 원인 - 남성 요인', '불임 원인 - 배란 장애', '불임 원인 - 여성 요인', '불임 원인 - 자궁경부 문제', '불임 원인 - 자궁내막증', '불임 원인 - 정자 농도', '불임 원인 - 정자 면역학적 요인', '불임 원인 - 정자 운동성', '불임 원인 - 정자 형태', '배아 생성 주요 이유', '동결 배아 사용 여부', '신선 배아 사용 여부', '기증 배아 사용 여부', '대리모 여부', '난자 채취 경과일', '임신 성공 여부']
ID            object
시술 시기 코드      object
시술 당시 나이      object
시술 유형         object
특정 시술 유형      object
              ...
대리모 여부          bool
난자 채취 경과일       bool
난자 혼합 경과일    float64
배아 이식 경과일    float64
임신 성공 여부        bool
Length: 62, dtype: object

### '정자 나이', '난자 나이' 컬럼 만들고 불필요한 컬럼 삭제

'시술 당시 나이', '정자 기증자 나이', '난자 기증자 나이', '난자 출처', '정자 출처' 컬럼을 삭제해도 된다.

In [58]:
import pandas as pd

def categorize_egg_age(row):
    # 난자 나이 통합
    egg_age = row['난자 기증자 나이'] if '난자 기증자 나이' in row else '알 수 없음'

    if egg_age in ['만21-25세', '만26-30세', '만31-35세', '만18-34세']:
        category = '건강한 난자'
    elif egg_age in ['만35-37세', '만38-39세']:
        category = '노화가 진행 중인 난자'
    elif egg_age in ['만40-42세', '만43-44세', '만45-50세']:
        category = '노화된 난자'
    else:
        category = '알 수 없음'
    
    return category

# 난자 나이 카테고리화 적용
df['난자 나이 카테고리'] = df.apply(categorize_egg_age, axis=1)

# '알 수 없음' 데이터 제거
df = df[df['난자 나이 카테고리'] != '알 수 없음']

# 불필요한 컬럼 삭제
df = df.drop(columns=['시술 당시 나이', '정자 기증자 나이', '난자 기증자 나이', '난자 출처', '정자 출처'])

df_young = df[df['난자 나이 카테고리'] == '건강한 난자'].drop(columns=['난자 나이 카테고리'])
df_middle = df[df['난자 나이 카테고리'] == '노화가 진행 중인 난자'].drop(columns=['난자 나이 카테고리'])
df_old = df[df['난자 나이 카테고리'] == '노화된 난자'].drop(columns=['난자 나이 카테고리'])

In [60]:
df_young.columns

# df_young의 컬럼 개수
print("건강한 난자 컬럼 개수:", len(df_young.columns))

건강한 난자 컬럼 개수: 57

In [55]:
print(df_young['임신 성공 여부'].value_counts())
print(df_middle['임신 성공 여부'].value_counts())
print(df_old['임신 성공 여부'].value_counts())

임신 성공 여부
False    76990
True     36737
Name: count, dtype: int64
임신 성공 여부
False    70435
True     23630
Name: count, dtype: int64
임신 성공 여부
False    42152
True      5784
Name: count, dtype: int64

## 시도하기

### 난자 연령별로 구분한 데이터프레임에서 bool 타입 컬럼들의 값 비율 알아보기

In [42]:
def calculate_bool_ratios(df, col):
    false_count = (df[col] == False).sum()  # False값의 수
    true_count = (df[col] == True).sum()    # True값의 수

    if true_count > 0:
        ratio = false_count / true_count
        return f"{false_count}:{true_count} -> {ratio:.2f}:1"
    else:
        return f"{false_count}:{true_count} -> Uncomparable (div by zero)"

# df의 bool 타입 컬럼
bool_columns = df.select_dtypes(include=bool).columns

# 각 연령대별 데이터프레임에 대해 비율 계산
df_age_groups = {
    "만18-34세": df_18_34,
    "만35-37세": df_35_37,
    "만38-39세": df_38_39,
    "만40-42세": df_40_42,
    "만43-44세": df_43_44,
    "만45-50세": df_45_50,
    "알 수 없음": df_unknown,
    "만20세 이하": df_20_under
}

# 각 컬럼에 대해 연령대별 비율 계산
column_ratios = {col: {} for col in bool_columns}

for col in bool_columns:
    for label, df_subset in df_age_groups.items():
        column_ratios[col][label] = calculate_bool_ratios(df_subset, col)


print("False : True 비율")

# 결과 출력
for col in bool_columns:
    print(f"Boolean ratios for column '{col}':")
    for label, ratio in column_ratios[col].items():
        print(f"  {label}: {ratio}")
    print()

False : True 비율
Boolean ratios for column '배란 자극 여부':
  만18-34세: 28101:85626 -> 0.33:1
  만35-37세: 10582:45617 -> 0.23:1
  만38-39세: 7570:30296 -> 0.25:1
  만40-42세: 7873:26551 -> 0.30:1
  만43-44세: 2711:7294 -> 0.37:1
  만45-50세: 1494:2013 -> 0.74:1
  알 수 없음: 6:323 -> 0.02:1
  만20세 이하: 294:0 -> Uncomparable (div by zero)

Boolean ratios for column '단일 배아 이식 여부':
  만18-34세: 77706:36021 -> 2.16:1
  만35-37세: 42665:13534 -> 3.15:1
  만38-39세: 32370:5496 -> 5.89:1
  만40-42세: 31839:2585 -> 12.32:1
  만43-44세: 9515:490 -> 19.42:1
  만45-50세: 3332:175 -> 19.04:1
  알 수 없음: 329:0 -> Uncomparable (div by zero)
  만20세 이하: 212:82 -> 2.59:1

Boolean ratios for column '남성 주 불임 원인':
  만18-34세: 111355:2372 -> 46.95:1
  만35-37세: 54441:1758 -> 30.97:1
  만38-39세: 36433:1433 -> 25.42:1
  만40-42세: 33117:1307 -> 25.34:1
  만43-44세: 9698:307 -> 31.59:1
  만45-50세: 3379:128 -> 26.40:1
  알 수 없음: 329:0 -> Uncomparable (div by zero)
  만20세 이하: 289:5 -> 57.80:1

Boolean ratios for column '남성 부 불임 원인':
  만18-34세: 112760:967 -> 116.61:1
  만35-37세: 55453:746 -> 74.33:1
  만38-39세: 37219:647 -> 57.53:1
  만40-42세: 33744:680 -> 49.62:1
  만43-44세: 9788:217 -> 45.11:1
  만45-50세: 3404:103 -> 33.05:1
  알 수 없음: 329:0 -> Uncomparable (div by zero)
  만20세 이하: 292:2 -> 146.00:1

Boolean ratios for column '여성 주 불임 원인':
  만18-34세: 111120:2607 -> 42.62:1
  만35-37세: 54286:1913 -> 28.38:1
  만38-39세: 36348:1518 -> 23.94:1
  만40-42세: 33063:1361 -> 24.29:1
  만43-44세: 9666:339 -> 28.51:1
  만45-50세: 3374:133 -> 25.37:1
  알 수 없음: 329:0 -> Uncomparable (div by zero)
  만20세 이하: 289:5 -> 57.80:1

Boolean ratios for column '여성 부 불임 원인':
  만18-34세: 112876:851 -> 132.64:1
  만35-37세: 55529:670 -> 82.88:1
  만38-39세: 37247:619 -> 60.17:1
  만40-42세: 33725:699 -> 48.25:1
  만43-44세: 9784:221 -> 44.27:1
  만45-50세: 3383:124 -> 27.28:1
  알 수 없음: 329:0 -> Uncomparable (div by zero)
  만20세 이하: 291:3 -> 97.00:1

Boolean ratios for column '부부 주 불임 원인':
  만18-34세: 110950:2777 -> 39.95:1
  만35-37세: 54161:2038 -> 26.58:1
  만38-39세: 36207:1659 -> 21.82:1
  만40-42세: 32937:1487 -> 22.15:1
  만43-44세: 9644:361 -> 26.71:1
  만45-50세: 3358:149 -> 22.54:1
  알 수 없음: 329:0 -> Uncomparable (div by zero)
  만20세 이하: 288:6 -> 48.00:1

Boolean ratios for column '부부 부 불임 원인':
  만18-34세: 113132:595 -> 190.14:1
  만35-37세: 55718:481 -> 115.84:1
  만38-39세: 37437:429 -> 87.27:1
  만40-42세: 33925:499 -> 67.99:1
  만43-44세: 9841:164 -> 60.01:1
  만45-50세: 3429:78 -> 43.96:1
  알 수 없음: 329:0 -> Uncomparable (div by zero)
  만20세 이하: 293:1 -> 293.00:1

Boolean ratios for column '불명확 불임 원인':
  만18-34세: 90175:23552 -> 3.83:1
  만35-37세: 41068:15131 -> 2.71:1
  만38-39세: 26643:11223 -> 2.37:1
  만40-42세: 24000:10424 -> 2.30:1
  만43-44세: 7006:2999 -> 2.34:1
  만45-50세: 2615:892 -> 2.93:1
  알 수 없음: 329:0 -> Uncomparable (div by zero)
  만20세 이하: 240:54 -> 4.44:1

Boolean ratios for column '불임 원인 - 난관 질환':
  만18-34세: 97169:16558 -> 5.87:1
  만35-37세: 47860:8339 -> 5.74:1
  만38-39세: 32512:5354 -> 6.07:1
  만40-42세: 30226:4198 -> 7.20:1
  만43-44세: 9157:848 -> 10.80:1
  만45-50세: 3256:251 -> 12.97:1
  알 수 없음: 329:0 -> Uncomparable (div by zero)
  만20세 이하: 285:9 -> 31.67:1

Boolean ratios for column '불임 원인 - 남성 요인':
  만18-34세: 67109:46618 -> 1.44:1
  만35-37세: 34765:21434 -> 1.62:1
  만38-39세: 24435:13431 -> 1.82:1
  만40-42세: 23718:10706 -> 2.22:1
  만43-44세: 7535:2470 -> 3.05:1
  만45-50세: 2745:762 -> 3.60:1
  알 수 없음: 329:0 -> Uncomparable (div by zero)
  만20세 이하: 249:45 -> 5.53:1

Boolean ratios for column '불임 원인 - 배란 장애':
  만18-34세: 94351:19376 -> 4.87:1
  만35-37세: 49283:6916 -> 7.13:1
  만38-39세: 34157:3709 -> 9.21:1
  만40-42세: 31841:2583 -> 12.33:1
  만43-44세: 9395:610 -> 15.40:1
  만45-50세: 3292:215 -> 15.31:1
  알 수 없음: 329:0 -> Uncomparable (div by zero)
  만20세 이하: 277:17 -> 16.29:1

Boolean ratios for column '불임 원인 - 여성 요인':
  만18-34세: 113727:0 -> Uncomparable (div by zero)
  만35-37세: 56199:0 -> Uncomparable (div by zero)
  만38-39세: 37866:0 -> Uncomparable (div by zero)
  만40-42세: 34424:0 -> Uncomparable (div by zero)
  만43-44세: 10005:0 -> Uncomparable (div by zero)
  만45-50세: 3507:0 -> Uncomparable (div by zero)
  알 수 없음: 329:0 -> Uncomparable (div by zero)
  만20세 이하: 294:0 -> Uncomparable (div by zero)

Boolean ratios for column '불임 원인 - 자궁경부 문제':
  만18-34세: 113723:4 -> 28430.75:1
  만35-37세: 56195:4 -> 14048.75:1
  만38-39세: 37866:0 -> Uncomparable (div by zero)
  만40-42세: 34422:2 -> 17211.00:1
  만43-44세: 10005:0 -> Uncomparable (div by zero)
  만45-50세: 3507:0 -> Uncomparable (div by zero)
  알 수 없음: 329:0 -> Uncomparable (div by zero)
  만20세 이하: 294:0 -> Uncomparable (div by zero)

Boolean ratios for column '불임 원인 - 자궁내막증':
  만18-34세: 105645:8082 -> 13.07:1
  만35-37세: 51514:4685 -> 11.00:1
  만38-39세: 34918:2948 -> 11.84:1
  만40-42세: 32345:2079 -> 15.56:1
  만43-44세: 9601:404 -> 23.76:1
  만45-50세: 3413:94 -> 36.31:1
  알 수 없음: 329:0 -> Uncomparable (div by zero)
  만20세 이하: 284:10 -> 28.40:1

Boolean ratios for column '불임 원인 - 정자 농도':
  만18-34세: 113601:126 -> 901.60:1
  만35-37세: 56142:57 -> 984.95:1
  만38-39세: 37823:43 -> 879.60:1
  만40-42세: 34384:40 -> 859.60:1
  만43-44세: 9998:7 -> 1428.29:1
  만45-50세: 3504:3 -> 1168.00:1
  알 수 없음: 329:0 -> Uncomparable (div by zero)
  만20세 이하: 294:0 -> Uncomparable (div by zero)

Boolean ratios for column '불임 원인 - 정자 면역학적 요인':
  만18-34세: 113727:0 -> Uncomparable (div by zero)
  만35-37세: 56198:1 -> 56198.00:1
  만38-39세: 37866:0 -> Uncomparable (div by zero)
  만40-42세: 34424:0 -> Uncomparable (div by zero)
  만43-44세: 10005:0 -> Uncomparable (div by zero)
  만45-50세: 3507:0 -> Uncomparable (div by zero)
  알 수 없음: 329:0 -> Uncomparable (div by zero)
  만20세 이하: 294:0 -> Uncomparable (div by zero)

Boolean ratios for column '불임 원인 - 정자 운동성':
  만18-34세: 113690:37 -> 3072.70:1
  만35-37세: 56173:26 -> 2160.50:1
  만38-39세: 37845:21 -> 1802.14:1
  만40-42세: 34414:10 -> 3441.40:1
  만43-44세: 10002:3 -> 3334.00:1
  만45-50세: 3507:0 -> Uncomparable (div by zero)
  알 수 없음: 329:0 -> Uncomparable (div by zero)
  만20세 이하: 294:0 -> Uncomparable (div by zero)

Boolean ratios for column '불임 원인 - 정자 형태':
  만18-34세: 113665:62 -> 1833.31:1
  만35-37세: 56172:27 -> 2080.44:1
  만38-39세: 37841:25 -> 1513.64:1
  만40-42세: 34398:26 -> 1323.00:1
  만43-44세: 10003:2 -> 5001.50:1
  만45-50세: 3506:1 -> 3506.00:1
  알 수 없음: 329:0 -> Uncomparable (div by zero)
  만20세 이하: 294:0 -> Uncomparable (div by zero)

Boolean ratios for column '배아 생성 주요 이유':
  만18-34세: 1106:112621 -> 0.01:1
  만35-37세: 722:55477 -> 0.01:1
  만38-39세: 503:37363 -> 0.01:1
  만40-42세: 410:34014 -> 0.01:1
  만43-44세: 122:9883 -> 0.01:1
  만45-50세: 51:3456 -> 0.01:1
  알 수 없음: 329:0 -> Uncomparable (div by zero)
  만20세 이하: 0:294 -> 0.00:1

Boolean ratios for column '동결 배아 사용 여부':
  만18-34세: 97118:16609 -> 5.85:1
  만35-37세: 47156:9043 -> 5.21:1
  만38-39세: 31587:6279 -> 5.03:1
  만40-42세: 28622:5802 -> 4.93:1
  만43-44세: 8371:1634 -> 5.12:1
  만45-50세: 2833:674 -> 4.20:1
  알 수 없음: 328:1 -> 328.00:1
  만20세 이하: 210:84 -> 2.50:1

Boolean ratios for column '신선 배아 사용 여부':
  만18-34세: 18649:95078 -> 0.20:1
  만35-37세: 10453:45746 -> 0.23:1
  만38-39세: 7297:30569 -> 0.24:1
  만40-42세: 6784:27640 -> 0.25:1
  만43-44세: 2025:7980 -> 0.25:1
  만45-50세: 922:2585 -> 0.36:1
  알 수 없음: 1:328 -> 0.00:1
  만20세 이하: 84:210 -> 0.40:1

Boolean ratios for column '기증 배아 사용 여부':
  만18-34세: 111689:2038 -> 54.80:1
  만35-37세: 56115:84 -> 668.04:1
  만38-39세: 37796:70 -> 539.94:1
  만40-42세: 34331:93 -> 369.15:1
  만43-44세: 9937:68 -> 146.13:1
  만45-50세: 3440:67 -> 51.34:1
  알 수 없음: 329:0 -> Uncomparable (div by zero)
  만20세 이하: 256:38 -> 6.74:1

Boolean ratios for column '대리모 여부':
  만18-34세: 112968:759 -> 148.84:1
  만35-37세: 56109:90 -> 623.43:1
  만38-39세: 37791:75 -> 503.88:1
  만40-42세: 34362:62 -> 554.23:1
  만43-44세: 9977:28 -> 356.32:1
  만45-50세: 3487:20 -> 174.35:1
  알 수 없음: 324:5 -> 64.80:1
  만20세 이하: 284:10 -> 28.40:1

Boolean ratios for column '난자 채취 경과일':
  만18-34세: 113727:0 -> Uncomparable (div by zero)
  만35-37세: 56199:0 -> Uncomparable (div by zero)
  만38-39세: 37866:0 -> Uncomparable (div by zero)
  만40-42세: 34424:0 -> Uncomparable (div by zero)
  만43-44세: 10005:0 -> Uncomparable (div by zero)
  만45-50세: 3507:0 -> Uncomparable (div by zero)
  알 수 없음: 329:0 -> Uncomparable (div by zero)
  만20세 이하: 294:0 -> Uncomparable (div by zero)

Boolean ratios for column '임신 성공 여부':
  만18-34세: 76990:36737 -> 2.10:1
  만35-37세: 40624:15575 -> 2.61:1
  만38-39세: 29811:8055 -> 3.70:1
  만40-42세: 29455:4969 -> 5.93:1
  만43-44세: 9346:659 -> 14.18:1
  만45-50세: 3351:156 -> 21.48:1
  알 수 없음: 329:0 -> Uncomparable (div by zero)
  만20세 이하: 217:77 -> 2.82:1

In [43]:
bool_columns

Index(['배란 자극 여부', '단일 배아 이식 여부', '남성 주 불임 원인', '남성 부 불임 원인', '여성 주 불임 원인',
       '여성 부 불임 원인', '부부 주 불임 원인', '부부 부 불임 원인', '불명확 불임 원인', '불임 원인 - 난관 질환',
       '불임 원인 - 남성 요인', '불임 원인 - 배란 장애', '불임 원인 - 여성 요인', '불임 원인 - 자궁경부 문제',
       '불임 원인 - 자궁내막증', '불임 원인 - 정자 농도', '불임 원인 - 정자 면역학적 요인',
       '불임 원인 - 정자 운동성', '불임 원인 - 정자 형태', '배아 생성 주요 이유', '동결 배아 사용 여부',
       '신선 배아 사용 여부', '기증 배아 사용 여부', '대리모 여부', '난자 채취 경과일', '임신 성공 여부'],
      dtype='object')

### IVF 환자와 DI 환자, 두 개의 데이터프레임으로 나누기

In [60]:
df_ivf = df[df['시술 유형'] == "IVF"]
df_di = df[df['시술 유형'] == "DI"]

df_ivf = df_ivf[interest_col]
df_di = df_di[interest_col]

### IVF 환자 데이터프레임에서 연관 컬럼 확인하기 w/ 도메인 지식

In [64]:
# 수치형 컬럼 확인하기
numeric_cols = df_ivf.select_dtypes(include=['int64', 'float64']).columns
numeric_cols

Index(['총 생성 배아 수', '미세주입된 난자 수', '미세주입에서 생성된 배아 수', '이식된 배아 수', '미세주입 배아 이식 수', '저장된 배아 수', '미세주입 후 저장된 배아 수', '해동된 배아 수', '해동 난자 수', '수집된 신선 난자 수', '저장된 신선 난자 수', '혼합된 난자 수', '파트너 정자와 혼합된 난자 수', '기증자 정자와 혼합된 난자 수', '난자 혼합 경과일', '배아 이식 경과일'], dtype='object')

In [13]:
# 범주형 컬럼 확인하기
categorical_cols = df_ivf.select_dtypes(include=['object']).columns
categorical_cols

Index(['시술 당시 나이', '시술 유형', '특정 시술 유형', '배란 유도 유형', '총 시술 횟수', '클리닉 내 총 시술 횟수',
       'IVF 시술 횟수', 'DI 시술 횟수', '총 임신 횟수', 'IVF 임신 횟수', 'DI 임신 횟수', '총 출산 횟수',
       'IVF 출산 횟수', 'DI 출산 횟수', '난자 출처', '정자 출처', '난자 기증자 나이', '정자 기증자 나이'],
      dtype='object')

In [65]:
# bool 컬럼 확인하기
bool_cols = df_ivf.select_dtypes(include=['bool']).columns
bool_cols

Index(['배란 자극 여부', '단일 배아 이식 여부', '남성 주 불임 원인', '남성 부 불임 원인', '여성 주 불임 원인', '여성 부 불임 원인', '부부 주 불임 원인', '부부 부 불임 원인', '불명확 불임 원인', '불임 원인 - 난관 질환', '불임 원인 - 남성 요인', '불임 원인 - 배란 장애', '불임 원인 - 여성 요인', '불임 원인 - 자궁경부 문제', '불임 원인 - 자궁내막증', '불임 원인 - 정자 농도', '불임 원인 - 정자 면역학적 요인', '불임 원인 - 정자 운동성', '불임 원인 - 정자 형태', '동결 배아 사용 여부', '신선 배아 사용 여부', '기증 배아 사용 여부', '대리모 여부', '난자 채취 경과일', '임신 성공 여부'], dtype='object')

### 주제: 불임 원인

In [62]:
# 주제: 불임 원인
causes_of_infertility_cols = ['남성 주 불임 원인',
 '남성 부 불임 원인',
 '여성 주 불임 원인',
 '여성 부 불임 원인',
 '부부 주 불임 원인',
 '부부 부 불임 원인',
 '불명확 불임 원인',
 '불임 원인 - 난관 질환',
 '불임 원인 - 남성 요인',
 '불임 원인 - 배란 장애',
 '불임 원인 - 여성 요인',
 '불임 원인 - 자궁경부 문제',
 '불임 원인 - 자궁내막증',
 '불임 원인 - 정자 농도',
 '불임 원인 - 정자 면역학적 요인',
 '불임 원인 - 정자 운동성',
 '불임 원인 - 정자 형태']

df_ivf_causes_of_infertility = df_ivf[causes_of_infertility_cols]

In [63]:
df_ivf_causes_of_infertility[df_ivf_causes_of_infertility['남성 주 불임 원인'] == 1][0:30]

      남성 주 불임 원인  남성 부 불임 원인  여성 주 불임 원인  여성 부 불임 원인  부부 주 불임 원인  부부 부 불임 원인  불명확 불임 원인  불임 원인 - 난관 질환  불임 원인 - 남성 요인  불임 원인 - 배란 장애  불임 원인 - 여성 요인  불임 원인 - 자궁경부 문제  불임 원인 - 자궁내막증  불임 원인 - 정자 농도  불임 원인 - 정자 면역학적 요인  불임 원인 - 정자 운동성  불임 원인 - 정자 형태
152         True       False        True       False        True       False       True          False          False          False          False            False          False          False               False           False          False
194         True       False        True       False        True       False       True          False          False          False          False            False          False          False               False           False          False
224         True       False        True       False        True       False      False          False           True          False          False            False          False          False               False           False          False
301         True       False        True       False        True       False      False           True          False           True          False            False          False          False               False           False          False
372         True       False       False        True        True       False      False           True          False          False          False            False          False          False               False           False          False
414         True       False        True       False        True       False      False          False          False          False          False            False           True          False               False           False          False
440         True       False        True       False        True       False      False          False           True           True          False            False          False          False               False           False          False
478         True       False        True       False        True       False       True          False          False          False          False            False          False          False               False           False          False
498         True       False        True       False        True       False      False           True          False           True          False            False           True          False               False           False          False
522         True       False        True       False        True       False      False          False          False          False          False            False           True          False               False           False          False
567         True       False        True       False        True       False       True          False          False          False          False            False          False          False               False           False          False
605         True       False        True       False        True       False       True          False          False          False          False            False          False          False               False           False          False
626         True       False       False        True        True       False      False          False           True          False          False            False          False          False               False           False          False
721         True       False        True       False        True       False      False          False           True          False          False            False          False          False               False           False          False
781         True       False        True       False        True       False      False          False           True          False          False            False          False          False               False           False          False
828         True       False        True       False        True       False      False          False           True          False          False            False          False          False               False           False          False
871         True       False        True       False        True       False       True          False          False          False          False            False          False          False               False           False          False
904         True       False        True       False        True       False       True          False          False          False          False            False          False          False               False           False          False
919         True       False        True       False        True       False      False          False           True          False          False            False          False          False               False           False          False
926         True       False        True       False        True       False      False          False          False           True          False            False          False          False               False           False          False
969         True       False        True       False        True       False      False          False          False           True          False            False          False          False               False           False          False
989         True       False        True       False        True       False      False          False           True          False          False            False          False          False               False           False          False
1002        True       False        True       False        True       False      False          False           True          False          False            False          False          False               False           False          False
1018        True       False       False        True        True       False      False          False           True          False          False            False          False          False               False           False          False
1047        True       False        True       False        True       False       True          False          False          False          False            False          False          False               False           False          False
1084        True       False        True       False        True       False       True          False          False          False          False            False          False          False               False           False          False
1086        True       False        True       False        True       False      False          False           True          False          False            False          False          False               False           False          False
1116        True       False        True       False        True       False      False          False           True          False          False            False          False          False               False           False          False
1147        True       False       False        True        True       False      False           True          False          False          False            False          False          False               False           False          False
1168        True       False        True       False        True       False       True          False          False          False          False            False          False          False               False           False          False

### 주제: 난자

In [67]:
temp = df_ivf[['시술 당시 나이', '난자 출처', '정자 출처', '난자 기증자 나이', '정자 기증자 나이', '대리모 여부', '난자 채취 경과일', '난자 혼합 경과일']]
temp[temp['난자 기증자 나이'] != temp['시술 당시 나이']]

       시술 당시 나이  난자 출처   정자 출처 난자 기증자 나이 정자 기증자 나이  대리모 여부  난자 채취 경과일  난자 혼합 경과일
6       만18-34세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
22      만40-42세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
40      만18-34세  기증 제공   기증 제공   만31-35세   만26-30세   False      False        0.0
79      만45-50세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
100     만18-34세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
116     만45-50세  기증 제공   기증 제공   만31-35세   만21-25세   False      False        0.0
129     만18-34세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
204     만43-44세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
206     만18-34세  기증 제공   기증 제공   만31-35세   만41-45세    True      False        0.0
230     만45-50세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
267     만45-50세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
280     만35-37세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
284     만45-50세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
302     만40-42세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
313     만45-50세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
345     만43-44세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
347     만40-42세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
349     만35-37세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
356     만35-37세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
370     만18-34세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
373     만45-50세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
411     만18-34세  기증 제공   기증 제공   만26-30세   만26-30세   False      False        0.0
413     만45-50세  기증 제공   기증 제공   만26-30세    알 수 없음   False      False        0.0
450     만40-42세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
470     만35-37세  기증 제공   기증 제공   만31-35세   만21-25세   False      False        0.0
490     만38-39세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
511     만45-50세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
528     만18-34세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
545     만18-34세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
558     만18-34세  기증 제공   기증 제공   만31-35세   만36-40세    True      False        0.0
567     만43-44세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
595     만45-50세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
610     만43-44세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
620     만45-50세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
621     만45-50세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
660     만45-50세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
665     만38-39세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
675     만45-50세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
688     만18-34세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
698     만45-50세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
716     만45-50세  기증 제공   기증 제공   만31-35세   만26-30세   False      False        0.0
785     만40-42세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
790     만18-34세  기증 제공   기증 제공   만26-30세   만36-40세    True      False        0.0
801     만38-39세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
806     만40-42세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
820     만40-42세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
898     만45-50세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
900     만45-50세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
908     만45-50세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
910     만35-37세  기증 제공   기증 제공   만31-35세   만20세 이하   False      False        0.0
923     만18-34세  기증 제공   기증 제공   만31-35세   만31-35세    True      False        0.0
927     만40-42세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
933     만40-42세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
945     만45-50세  기증 제공   기증 제공   만21-25세   만36-40세   False      False        0.0
955     만45-50세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
961     만40-42세  기증 제공   기증 제공   만26-30세   만31-35세   False      False        0.0
984     만43-44세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
1000    만35-37세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
1002    만40-42세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
1005    만40-42세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
1023    만18-34세  기증 제공   기증 제공   만26-30세   만26-30세   False      False        0.0
1049    만43-44세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
1052    만35-37세  기증 제공  배우자 제공   만20세 이하    알 수 없음   False      False        0.0
1103    만40-42세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
1111    만18-34세  기증 제공   기증 제공   만26-30세   만36-40세   False      False        0.0
1113    만18-34세  기증 제공   기증 제공   만31-35세   만20세 이하   False      False        0.0
1124    만45-50세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
1130    만18-34세  기증 제공   기증 제공   만26-30세   만21-25세   False      False        0.0
1164    만40-42세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
1177    만40-42세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
1189    만40-42세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
1215    만18-34세  기증 제공   기증 제공   만26-30세   만36-40세    True      False        0.0
1220    만18-34세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
1226    만45-50세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
1253    만43-44세  기증 제공   기증 제공   만21-25세   만36-40세   False      False        0.0
1256    만38-39세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
1270    만43-44세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
1318    만45-50세  기증 제공   기증 제공   만26-30세   만41-45세   False      False        0.0
1363    만40-42세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
1381    만45-50세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
1420    만45-50세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
1423    만35-37세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
1437    만45-50세  기증 제공   기증 제공   만31-35세   만41-45세   False      False        0.0
1448    만35-37세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
1458    만45-50세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
1462    만40-42세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
1463    만45-50세  기증 제공   기증 제공   만31-35세   만36-40세   False      False        0.0
1476    만45-50세  기증 제공   기증 제공   만31-35세   만31-35세   False      False        0.0
1501    만45-50세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
1561    만18-34세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
1562    만45-50세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
1578    만40-42세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
1581    만38-39세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
1605    만45-50세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
1623    만40-42세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
1626    만18-34세  기증 제공   기증 제공   만31-35세   만21-25세   False      False        0.0
1639    만43-44세  기증 제공   기증 제공   만26-30세   만36-40세   False      False        0.0
1703    만45-50세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
1709    만40-42세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
1739    만40-42세  기증 제공   기증 제공   만26-30세   만31-35세   False      False        0.0
1751    만43-44세  기증 제공  배우자 제공   만20세 이하    알 수 없음   False      False        0.0
1756    만45-50세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
1799    만45-50세  기증 제공   기증 제공   만21-25세   만36-40세   False      False        0.0
1818    만18-34세  기증 제공   기증 제공   만31-35세   만26-30세   False      False        0.0
1826    만18-34세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
1833    만35-37세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
1853    만43-44세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
1867    만45-50세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
1890    만18-34세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
1910    만43-44세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
1945    만35-37세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
1949    만45-50세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
1989    만45-50세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
2012    만45-50세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
2013    만35-37세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
2027    만35-37세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
2034    만40-42세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
2042    만43-44세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
2083    만38-39세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
2102    만45-50세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
2109    만43-44세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
2157    만43-44세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
2162    만40-42세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
2168    만35-37세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
2197    만45-50세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
2198    만40-42세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
2202    만43-44세  기증 제공  배우자 제공   만20세 이하    알 수 없음   False      False        0.0
2211    만43-44세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
2214    만45-50세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
2215    만45-50세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
2218    만40-42세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
2234    만18-34세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
2292    만40-42세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
2308    만18-34세  기증 제공   기증 제공   만31-35세   만36-40세    True      False        0.0
2368    만38-39세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
2369    만40-42세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
2425    만45-50세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
2432    만40-42세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
2449    만45-50세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
2492    만40-42세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
2526    만38-39세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
2531    만43-44세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
2578    만18-34세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
2584    만45-50세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
2597    만43-44세  기증 제공   기증 제공   만31-35세   만36-40세   False      False        0.0
2635    만35-37세  기증 제공   기증 제공   만31-35세   만31-35세   False      False        0.0
2639    만45-50세  기증 제공   기증 제공   만31-35세   만41-45세   False      False        0.0
2667    만35-37세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
2669    만43-44세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
2679    만43-44세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
2689    만40-42세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
2711    만18-34세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
2719    만45-50세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
2727    만35-37세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
2730    만45-50세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
2731    만40-42세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
2741    만45-50세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
2780    만38-39세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
2785    만45-50세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
2800    만45-50세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
2826    만45-50세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
2863    만40-42세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
2886    만18-34세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
2892    만40-42세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
2896    만45-50세  기증 제공   기증 제공   만31-35세    알 수 없음   False      False        0.0
2942    만43-44세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
2972    만18-34세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
2998    만40-42세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
3010    만40-42세  기증 제공   기증 제공   만31-35세   만36-40세   False      False        0.0
3038    만45-50세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
3109    만40-42세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
3114    만45-50세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
3119    만45-50세  기증 제공   기증 제공   만31-35세   만21-25세   False      False        0.0
3124    만40-42세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
3136    만45-50세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
3163    만40-42세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
3185    만43-44세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
3187    만43-44세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
3195    만18-34세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
3206    만18-34세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
3230    만45-50세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
3269    만40-42세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
3278    만40-42세  기증 제공   기증 제공   만26-30세    알 수 없음   False      False        0.0
3305    만43-44세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
3307    만45-50세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
3387    만38-39세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
3393    만18-34세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
3408    만45-50세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
3414    만43-44세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
3424    만18-34세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
3430    만40-42세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
3435    만45-50세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
3446    만43-44세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
3458    만45-50세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
3479    만18-34세  기증 제공   기증 제공   만21-25세   만36-40세    True      False        0.0
3541    만43-44세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
3549    만45-50세  기증 제공   기증 제공   만26-30세   만26-30세   False      False        0.0
3579    만18-34세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
3599    만18-34세  기증 제공   기증 제공   만31-35세   만26-30세    True      False        0.0
3632    만18-34세  기증 제공   기증 제공   만26-30세   만41-45세   False      False        0.0
3687    만35-37세  기증 제공   기증 제공   만31-35세   만36-40세    True      False        0.0
3696    만43-44세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
3719    만45-50세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
3730    만38-39세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
3755    만43-44세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
3764    만18-34세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
3769    만40-42세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
3784    만43-44세  기증 제공   기증 제공   만26-30세   만36-40세   False      False        0.0
3823    만43-44세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
3859    만18-34세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
3861    만18-34세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
3896    만35-37세  기증 제공   기증 제공   만31-35세    알 수 없음   False      False        0.0
3909    만18-34세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
3920    만35-37세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
3923    만18-34세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
3924    만35-37세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
3942    만18-34세  기증 제공   기증 제공   만31-35세   만36-40세    True      False        0.0
3965    만40-42세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
3986    만45-50세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
3990    만43-44세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
4085    만18-34세  기증 제공   기증 제공   만31-35세   만21-25세   False      False        0.0
4099    만18-34세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
4120    만18-34세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
4133    만43-44세  기증 제공   기증 제공   만31-35세   만26-30세   False      False        0.0
4173    만40-42세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
4222    만40-42세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
4226    만40-42세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
4247    만45-50세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
4257    만45-50세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
4287    만45-50세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
4402    만40-42세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
4433    만43-44세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
4452    만35-37세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
4454    만45-50세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
4485    만45-50세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
4537    만38-39세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
4563    만40-42세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
4628    만43-44세  기증 제공   기증 제공   만26-30세   만31-35세   False      False        0.0
4678    만45-50세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
4697    만45-50세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
4701    만45-50세  기증 제공  배우자 제공   만31-35세    알 수 없음   False      False        0.0
4721    만38-39세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
4724    만35-37세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0
4749    만18-34세  기증 제공  배우자 제공   만21-25세    알 수 없음   False      False        0.0
4763    만43-44세  기증 제공  배우자 제공   만26-30세    알 수 없음   False      False        0.0

In [26]:
df_ivf[['배란 자극 여부', '배란 유도 유형', '단일 배아 이식 여부']][0:30]
df_ivf[['배란 자극 여부', '배란 유도 유형', '단일 배아 이식 여부']][0:30]

    배란 자극 여부    배란 유도 유형  단일 배아 이식 여부
0          1  기록되지 않은 시행          0.0
1          0      알 수 없음          0.0
2          1  기록되지 않은 시행          0.0
3          1  기록되지 않은 시행          0.0
4          1  기록되지 않은 시행          0.0
5          1  기록되지 않은 시행          0.0
6          0      알 수 없음          1.0
7          1  기록되지 않은 시행          0.0
8          1  기록되지 않은 시행          0.0
9          1  기록되지 않은 시행          0.0
10         0      알 수 없음          0.0
11         1  기록되지 않은 시행          0.0
12         0      알 수 없음          0.0
13         1  기록되지 않은 시행          0.0
15         1  기록되지 않은 시행          0.0
16         0      알 수 없음          0.0
17         1  기록되지 않은 시행          0.0
18         1  기록되지 않은 시행          0.0
19         0      알 수 없음          1.0
20         1  기록되지 않은 시행          0.0
21         1  기록되지 않은 시행          1.0
22         0      알 수 없음          1.0
23         1  기록되지 않은 시행          0.0
24         0      알 수 없음          1.0
25         0      알 수 없음          0.0
26         1  기록되지 않은 시행          0.0
27         1  기록되지 않은 시행          0.0
28         0      알 수 없음          0.0
29         1  기록되지 않은 시행          0.0
30         1  기록되지 않은 시행          0.0

In [49]:
df_embryo = df_ivf[['단일 배아 이식 여부', '이식된 배아 수', '임신 성공 여부']]
df_embryo[(df_embryo['이식된 배아 수'] == 0.0) & (df_embryo['단일 배아 이식 여부'] != 0)][0:50]
df_embryo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 250060 entries, 0 to 256350
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   단일 배아 이식 여부  250060 non-null  float64
 1   이식된 배아 수     250060 non-null  float64
 2   임신 성공 여부     250060 non-null  int64
dtypes: float64(2), int64(1)
memory usage: 7.6 MB

In [45]:
df_embryo[df_embryo['단일 배아 이식 여부'] != 0]['이식된 배아 수'].value_counts()

이식된 배아 수
1.0    58360
2.0       21
3.0        2
Name: count, dtype: int64

In [46]:
df_embryo[df_embryo['단일 배아 이식 여부'] != 0].value_counts()

단일 배아 이식 여부  이식된 배아 수  임신 성공 여부
1.0          1.0       0           36926
                       1           21434
             2.0       0              15
                       1               6
             3.0       0               2
Name: count, dtype: int64

In [47]:
df_ivf['임신 성공 여부'].value_counts()

임신 성공 여부
0    184643
1     65417
Name: count, dtype: int64